# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-11 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detections.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valMin', models.FloatField(null=True)),
                ('valMax', models.FloatField(null=True)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detections.Type'),
        ),
        migrations.AddField(
            model_name='detection',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='detections.Sensor'),
        ),
    ]
